"""Aumento tamanho da coluna password_hash para 256

Revision ID: 43c74097d663
Revises: 
Create Date: 2025-02-05 16:56:21.432455

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43c74097d663"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password_hash",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password_hash",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
